name: "Default Node.js CI"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Ref to trigger workflow"
        required: false
        default: "master"
      project_name:
        description: "Project package name"
        required: true
        
  workflow_call:
    inputs:
      ref:
        type: string
        description: "Ref to trigger workflow"
        required: false
        default: "master"
      project_name:
        type: string
        description: "Project package name"
        required: true
    outputs:
      image_ref:
        description: "Image ref"
        value: ${{ jobs.build.outputs.image_ref_run_number }}

jobs:
  build:
    name: Build ${{ inputs.project_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with: 
          ref: ${{ inputs.ref }}

      - uses: docker/setup-buildx-action@v1
        name: Setup Docker Buildx

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v2
        name: Setup Node
        with:
          node-version: "14"

      # https://github.com/microsoft/rushstack/issues/1847#issuecomment-993825253

      - name: Cache Rush
        uses: actions/cache@v2
        with:
          path: |
            common/temp/install-run
          key: ${{ runner.os }}-${{ hashFiles('rush.json') }}

      - name: Cache pnpm
        uses: actions/cache@v2
        with:
          path: |
            common/temp/pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install Dependencies
        run: |
          node common/scripts/install-run-rush.js install --no-link

      - name: Link Dependencies
        run: |
          node common/scripts/install-run-rush.js link

      - name: Build
        run: |
          node common/scripts/install-run-rush.js build -t ${{ inputs.project_name }} -p 1 -v

      - name: Rush Deploy
        run: |
          node common/scripts/install-run-rush.js deploy -p ${{ inputs.project_name }}

      # https://github.community/t/syntax-for-replacing-characters-in-string/17240
      # install-run-rush.js outputs unnecessary information, use tail to remove it
      # https://github.com/microsoft/rushstack/issues/2607
      - name: Build Info
        id: build_info
        run: |
          project_path=$(node common/scripts/install-run-rush.js list -o ${{ inputs.project_name }} -p --json | tail -n +6 | jq -r .projects[0].path)
          echo "Project path: $project_path"

          dockerfile_path="$project_path/Dockerfile"
          echo "Dockerfile path: $dockerfile_path"
          echo "::set-output name=dockerfile_path::$dockerfile_path"

          image_name="lani-${project_name##*/}"
          echo "Image name: $image_name"
          echo "::set-output name=image_name::$image_name"

          ref_escaped="${ref_raw////-}"
          echo "Escaped ref: $ref_escaped"
          echo "::set-output name=ref_escaped::$ref_escaped"
        env:
          project_name: ${{ inputs.project_name }}
          ref_raw: ${{ inputs.ref }}

      - name: Eval tag names
        id: tag_names
        run: |
          echo "::set-output name=image_ref::$image_name"
          echo "::set-output name=image_ref_run_number::$image_ref_run_number"
          echo "::set-output name=image_ref_sha::$image_ref_sha"
          echo "::set-output name=image_ref_branch::$image_ref_branch"
          echo "::set-output name=image_ref_latest::$image_ref_latest"
        env:
          image_ref_run_number: ghcr.io/${{ github.repository_owner }}/${{ steps.build_info.outputs.image_name }}:1.0.${{ github.run_number }}
          image_ref_sha: ghcr.io/${{ github.repository_owner }}/${{ steps.build_info.outputs.image_name }}:${{ github.sha }}
          image_ref_branch: ghcr.io/${{ github.repository_owner }}/${{ steps.build_info.outputs.image_name }}:${{ github.sha }}
          image_ref_latest: ghcr.io/${{ github.repository_owner }}/${{ steps.build_info.outputs.image_name }}:latest


      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: ${{ steps.build_info.outputs.dockerfile_path }}
          tags: >
            ${{ steps.tag_names.outputs.image_ref_run_number }},
            ${{ steps.tag_names.outputs.image_ref_sha }},
            ${{ steps.tag_names.outputs.image_ref_branch }},
            ${{ steps.tag_names.outputs.image_ref_latest }}

    outputs:
      image_ref_run_number: ${{ steps.tag_names.outputs.image_ref_run_number }}
      image_ref_sha: ${{ steps.tag_names.outputs.image_ref_sha }}
      image_ref_branch: ${{ steps.tag_names.outputs.image_ref_branch }}
      image_ref_latest: ${{ steps.tag_names.outputs.image_ref_latest }}
